### PR TITLE
Blog post generative AI

### PR DESCRIPTION
**Pull request by GG-OnDecentral**
- Added a blog post
- Changed "Start with a team" to "Join the community" in the title of the section

### CODE REVIEW

**Comment by decentral-foundation** [comment]
Needs work. See screenshots @GG-OnDecentral 

image


image

**Review by lingqingmeng — COMMENTED** [review]
Not ready for merge. CSS text overlaps with image for desktop 3/4 width and full width. Mobile CSS good

**Comment by GG-OnDecentral** [comment]
@lingqingmeng Please review again

**Comment by GG-OnDecentral** [comment]
@lingqingmeng Review again

**Review by lingqingmeng — APPROVED** [review]
looks good to me

**Pull request merged**
